# Generated by Django 4.2.5 on 2023-09-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='link',
        ),
    ]
